name: Rust
on: [push, pull_request]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - uses: raftario/setup-rust-action@releases/v1
    - name: Run tests
      run: cargo test -v
  check:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - uses: raftario/setup-rust-action@releases/v1
      with:
        install-rustfmt: true
        install-clippy: true
    - name: Check for clippy warnings
      if: github.event_name == 'pull_request'
      run: cargo clippy -- -D warnings
    - name: Check formatting
      if: github.event_name == 'pull_request'
      run: cargo fmt -v -- --check
      
