name: Rust checks
on: [pull_request]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - uses: raftario/setup-rust-action@v1
      with:
        install-rustfmt: true
        install-clippy: true
    - name: Check for clippy warnings
      run: cargo clippy -- -D warnings
    - name: Check formatting
      run: cargo fmt -v -- --check
      
