name: Rust
on: [push, pull_request]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      marix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Run tests
      run: cargo test --verbose
  check:
    needs: test
    runs-on: ${{ matrix.os }}
    strategy:
      marix:
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Check for clippy warnings
      if: github.event_name == 'pull_request'
      run: cargo clippy -- -D warnings
    - name: Check formatting
      if: github.event_name == 'pull_request'
      run: cargo fmt -- --check
      
