name: Rust tests
on: [push, pull_request]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - uses: raftario/setup-rust-action@v1
    - name: Run tests
      run: cargo test -v
